name: Deploy Azure Resources

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Azure Resources Job
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep Template
        id: validate-template
        uses: azure/arm-deploy@v1
        with:
          scope: "resourcegroup"
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: "./deploy.bicep"
          parameters: 
            objectId=${{ secrets.OBJECT_ID }}
            mainObjectId=${{ secrets.YASH_OBJECT_ID }} 
          failOnStdErr: false
          deploymentMode: "Validate"

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: "resourcegroup"
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: "./deploy.bicep"
          parameters:
            mainObjectId=${{ secrets.YASH_OBJECT_ID }} 
            objectId=${{ secrets.OBJECT_ID }}
          failOnStdErr: false
          deploymentMode: "Incremental"
