name: deploy.bicep
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: "resourcegroup"
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: "./deploy.bicep"
          parameters: objectId=${{ secrets.OBJECT_ID }}
          failOnStdErr: false
          deploymentMode: "Validate"

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: "resourcegroup"
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: "./deploy.bicep"
          parameters: objectId=${{ secrets.OBJECT_ID }}
          failOnStdErr: false
          deploymentMode: "Incremental"
