name: Run az cli command

on:
  workflow_dispatch:

jobs:
  destroy-resources:
    name: Run az cli command
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy Bicep Template"
        run: |
          az keyvault secret show --name ACRAdminUsername --vault-name kv-brewBicep-zh7xuvtrlmf
